In [1]:
# Importing Libraries

import numpy as np # if not pip install numpy | pip3 install numpy

# BACKGROUND

Multi-dimensional arrays library.

List are slow, Numpy arrays are fast.

Numpy uses fixed types. Like Int32, Int16, float32, Int8 ( single bite ).

When we iterate through this array, we don't have to type check everytime.

Numpy is contiguous memory. CPU have Single instruction Multiple data processing units which make numpy computational fast. Also, cache is more effectively utilized. Also, Numpy have more functionality than Lists like multiply, matrix multiplications and other computational stuff.

List is a contiguous array of pointers not of the various data-types.

Applications of Numpy :
- Have lot of Matlab functions. If Numpy doesn't work use scipy.
- Useful for Plotting ( Matplotlib ).
- Backend of many other frameworks ( Pandas, Digital Photography ).
- Machine Learning and Deep Learning.

In [10]:
a = np.array([1,2,3])
print(a,"\n") # a one-d array with degree : 1, Shape : 1 x 3 

b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b,"\n") # 2-D array

print(a.ndim,"\n",b.shape,"\n",a.dtype,"\n",b.dtype) # return dimension of numpy array, shape of the same, dtype : int32 by default and dtype : float64, 

[1 2 3] 

[[1. 2. 3.]
 [4. 5. 6.]] 

1 
 (2, 3) 
 int32 
 float64


In [18]:
a = np.array([1,2,3],dtype='int8') # size of 1 byte - Try to specify data-type to fit your data as tightly as possible
print(a.dtype,"\n",a.itemsize,"\n",a.size,"\n",a.nbytes,"\n",b.itemsize) # item size : return the bit size of the data-type, np.array.size : number of items, 

int8 
 1 
 3 
 3 
 8


# Accessing/Changing specific elements, rows, columns, etc.

In [28]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

print(a,"\n",a.shape,"\n",a[1,5],"\n",a[0,:],'\n',a[:2],'\n',a[0,1:-2:2]) # Get a specific element [r,c] ; [r,:] prints the entire column

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] 
 (2, 7) 
 13 
 [1 2 3 4 5 6 7] 
 [[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] 
 [2 4]


In [29]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [32]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b,'\n',b[0,1,:])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
 [3 4]


In [35]:
b[:,1,:] = [[1,2],[3,4]]
print(b)

[[[1 2]
  [1 2]]

 [[5 6]
  [3 4]]]


# Initializing different types of Arrays

In [36]:
# All 0's matrix

np.zeros((2,3,3)) # just input the shape you want for the array

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [39]:
# All 1's

np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [41]:
# Any other number

np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [42]:
# Any other number (full_like)

np.full_like(a,4) # the size of a was 2x7, and the number we wanted in their was 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [44]:
np.full(a.shape,4) # works same like the previous once

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
np.random.rand(4,2,3) # putting the shape directly

array([[[0.19316278, 0.54730918, 0.9440055 ],
        [0.89008509, 0.85672656, 0.92491974]],

       [[0.73316045, 0.44375778, 0.64661722],
        [0.21622688, 0.7585351 , 0.5133951 ]],

       [[0.36349293, 0.42543684, 0.43176078],
        [0.70098663, 0.66646544, 0.70254708]],

       [[0.599648  , 0.67595097, 0.53504524],
        [0.51919392, 0.04956357, 0.88231395]]])

In [47]:
np.random.random_sample(a.shape) # random matrix as the same shape of a

array([[0.00604841, 0.68910149, 0.18986063, 0.62949531, 0.16770735,
        0.02473097, 0.40838251],
       [0.27295543, 0.4030908 , 0.70609157, 0.50607273, 0.76988199,
        0.02466887, 0.80916734]])

In [51]:
# to get random integer values

np.random.randint(4,7,size=(3,3)) # 4 is the lowest & 7 is the highest value of the integer the random matrix could take

array([[5, 4, 6],
       [6, 4, 5],
       [4, 6, 5]])

In [52]:
# Declaring Identity matrix

np.identity(5) # identity matrix of size 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [53]:
# Repeat on a one-D array

arr = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
print(r1) # a one dimensional array

[1 1 1 2 2 2 3 3 3]


In [55]:
# Repeat on a two-D array

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0) # 0'th axis stands for rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [57]:
'''

Create the 2-D matrix :

1 1 1 1 1
1 0 0 0 1
1 0 9 0 1
1 0 0 0 1
1 1 1 1 1

'''

'\n\nCreate the 2-D matrix :\n\n1 1 1 1 1\n1 0 0 0 1\n1 0 9 0 1\n1 0 0 0 1\n1 1 1 1 1\n\n'

In [65]:
arr = np.ones((5,5),dtype='int8')

arr[1:4,1:4] = np.zeros((3,3),dtype='int8')

arr[2,2] = 9

print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Copying Numpy Arrays ( Be Careful !! )

In [66]:
a = np.array([1,2,3])
b = a
print(a,'\n',b)

[1 2 3] 
 [1 2 3]


In [67]:
b[0] = 100
print(a,'\n',b) # This is the concept of pointer

[100   2   3] 
 [100   2   3]


In [68]:
# so too actually copy use

b = a.copy()
b[0]=300
print(a,'\n',b)

[100   2   3] 
 [300   2   3]


# Mathematics

In [73]:
a = np.array([1,2,3,4])
print(a)

a = a + 2 # adds 2 to each element
print(a)

a = a - 2 # subtracts 2 from each element
print(a)

a = a*2 # multiply everything by 2
print(a)

a = a/2 # divide everything by 2
print(a)

a += 2 # adds 2 to each element
print(a)

a = a**2 # square's everything
print(a)

[1 2 3 4]
[3 4 5 6]
[1 2 3 4]
[2 4 6 8]
[1. 2. 3. 4.]
[3. 4. 5. 6.]
[ 9. 16. 25. 36.]


In [74]:
b = np.array([1,0,1,0])
print(a+b) # adds all elements along the axis = 0

[10. 16. 26. 36.]


In [75]:
# trignometric

a = np.sin(a) # sin of all values
print(a)

a = np.cos(a) # cosine off all values
print(a)

[ 0.41211849 -0.28790332 -0.13235175 -0.99177885]
[0.91627432 0.95884132 0.99125428 0.54720183]


# Linear Algebra

In [77]:
a = np.full((2,3),1) # 2x3 matrix of 1's
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b) # matrix multiplication function

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [79]:
c = np.identity(3) # an identity matrix
np.linalg.det(c) # find the determinant of c

1.0

# Statistics with Numpy

In [82]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)
print(np.min(stats),'\n',np.max(stats),'\n',np.min(stats,axis=1)) # prints the minimum in the whole numpy array

[[1 2 3]
 [4 5 6]]
1 
 6 
 [1 4]


In [83]:
print(np.sum(stats)) # prints the sum of the whole numpy array

21


In [111]:
print(np.unique(stats))

[1 2 3 4 5 6]


# Reorganizing Arrays

In [85]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2)) # reshaping is allowed, as long as it is valid reshaping
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [88]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v1]) # stacks lists vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [89]:
np.hstack([v1,v2]) # here the horizontal stack made a single list

array([1, 2, 3, 4, 5, 6, 7, 8])

In [91]:
h1 = [v1]
h2 = [v2]

np.hstack([h1,h2]) # joins them, necessary relation ; number of rows must be same

array([[1, 2, 3, 4, 5, 6, 7, 8]])

# Load Data from file

In [92]:
data_file_path = r'C:\Local Disk\Programming\Python Projects\Numpy\data.txt'

In [98]:
filedata = np.genfromtxt(data_file_path,delimiter=',') # creates a numpy array from the txt file

print(filedata)

filedata = filedata.astype('int32') # from float to int32

print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


# Boolean Masking & Advanced Indexing

In [99]:
filedata > 50 # get false or true and know that whether that specific location is greater than 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [101]:
filedata[filedata>50] # returns an array of only those values that are greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [102]:
# we can index with a list in NumPy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]] # indexed those spots based on a past of index_values enclosed in a list

array([2, 3, 9])

In [105]:
print(np.any(filedata>50,axis=0),'\n\n',np.all(filedata>50,axis=0)) # checks along the basis of rows - if any of the the column_values have values greater than 50

[False False False False  True  True False  True  True False False False
 False False False False  True  True] 

 [False False False False  True False False False False False False False
 False False False False False False]


In [107]:
((filedata>50) & (filedata<50)) # ands two numpy matrices of same shape

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [108]:
(~((filedata>50) & (filedata<50))) # the not for the same

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])